/*
 * Created on 29 Nov 2016 ( Time 11:52:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "tbl_bidderapprovaldetail"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_bidderapprovaldetail")
public class TblBidderApprovalDetail implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bidderApprovalId", nullable=false)
    private Integer    bidderapprovalid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="createdBy", nullable=false)
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn")
    private Date       createdon = new Date();

    @Column(name="isApproved", nullable=false)
    private Integer    isapproved   ;

    @Column(name="remarks")
    private String     remarks      ;

    @Column(name="companyid", nullable=false)
    private Integer    companyid    ;

    @Column(name="bidderid", nullable=false)
    private Integer    bidderid     ;

	// "finalsubmissionid" (column "finalSubmissionId") is not defined by itself because used as FK in a link 
	// "tenderid" (column "tenderid") is not defined by itself because used as FK in a link 
	// "envelopeid" (column "envelopeid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="finalSubmissionId", referencedColumnName="finalSubmissionId")
    private TblFinalsubmission tblFinalsubmission;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tenderid", referencedColumnName="tenderId")
    private TblTender tblTender   ;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="envelopeid", referencedColumnName="envelopeId")
    private TblTenderEnvelope tblTenderEnvelope;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblBidderApprovalDetail()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBidderapprovalid( Integer bidderapprovalid )
    {
        this.bidderapprovalid = bidderapprovalid ;
    }
    public Integer getBidderapprovalid()
    {
        return this.bidderapprovalid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : isApproved ( INT ) 
    public void setIsapproved( Integer isapproved )
    {
        this.isapproved = isapproved;
    }
    public Integer getIsapproved()
    {
        return this.isapproved;
    }

    //--- DATABASE MAPPING : remarks ( LONGTEXT ) 
    public void setRemarks( String remarks )
    {
        this.remarks = remarks;
    }
    public String getRemarks()
    {
        return this.remarks;
    }

    //--- DATABASE MAPPING : companyid ( INT ) 
    public void setCompanyid( Integer companyid )
    {
        this.companyid = companyid;
    }
    public Integer getCompanyid()
    {
        return this.companyid;
    }

    //--- DATABASE MAPPING : bidderid ( INT ) 
    public void setBidderid( Integer bidderid )
    {
        this.bidderid = bidderid;
    }
    public Integer getBidderid()
    {
        return this.bidderid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTblFinalsubmission( TblFinalsubmission tblFinalsubmission )
    {
        this.tblFinalsubmission = tblFinalsubmission;
    }
    public TblFinalsubmission getTblFinalsubmission()
    {
        return this.tblFinalsubmission;
    }

    public void setTblTender( TblTender tblTender )
    {
        this.tblTender = tblTender;
    }
    public TblTender getTblTender()
    {
        return this.tblTender;
    }

    public void setTblTenderenvelope( TblTenderEnvelope tblTenderenvelope )
    {
        this.tblTenderEnvelope = tblTenderenvelope;
    }
    public TblTenderEnvelope getTblTenderenvelope()
    {
        return this.tblTenderEnvelope;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(bidderapprovalid);
        sb.append("]:"); 
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        sb.append("|");
        sb.append(isapproved);
        // attribute 'remarks' not usable (type = String Long Text)
        sb.append("|");
        sb.append(companyid);
        sb.append("|");
        sb.append(bidderid);
        return sb.toString(); 
    } 

}