/*
 * Created on 24 Nov 2016 ( Time 10:54:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


@Entity
@Table(name="tbl_bidderstatusremarks")
public class TblBidderStatusRemarks implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bidderStatusRemarksId", nullable=false)
    public Integer    bidderStatusRemarksId    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bidderId", nullable=false)
    private Integer     bidderId  ;

    @Column(name="Remarks", nullable=false)
    private String    Remarks    ;

    @Column(name="type", nullable=false)
    private Integer   type    ;

    @Column(name="moduleId", nullable=false)
    private Integer   moduleId    ;

    

    public Integer getModuleId() {
		return moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public Integer getBidderStatusRemarksId() {
		return bidderStatusRemarksId;
	}

	public void setBidderStatusRemarksId(Integer bidderStatusRemarksId) {
		this.bidderStatusRemarksId = bidderStatusRemarksId;
	}

	public Integer getBidderId() {
		return bidderId;
	}

	public void setBidderId(Integer bidderId) {
		this.bidderId = bidderId;
	}

	public String getRemarks() {
		return Remarks;
	}

	public void setRemarks(String remarks) {
		Remarks = remarks;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        // attribute 'companyname' not usable (type = String Long Text)
        sb.append("|");
        return sb.toString(); 
    } 

}