/*
 * Created on 30 Nov 2016 ( Time 11:16:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "tbl_bidderapprovalhistory"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_bidderapprovalhistory")
public class TblBidderApprovalHistory implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="bidderApprovalHistoryId", nullable=false)
    private Integer    bidderapprovalhistoryid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bidderId", nullable=false)
    private Integer    bidderid     ;

    @Column(name="companyId", nullable=false)
    private Integer    companyid    ;

    @Column(name="createdBy")
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn")
    private Date       createdon = new Date()    ; 

    @Column(name="envelopeId", nullable=false)
    private Integer    envelopeid   ;

    @Column(name="finalSubmissionId", nullable=false)
    private Integer    finalsubmissionid ;

    @Column(name="isApproved")
    private Integer    isapproved   ;

    @Column(name="remarks")
    private String     remarks      ;

    @Column(name="tenderId", nullable=false)
    private Integer    tenderid     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblBidderApprovalHistory()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBidderapprovalhistoryid( Integer bidderapprovalhistoryid )
    {
        this.bidderapprovalhistoryid = bidderapprovalhistoryid ;
    }
    public Integer getBidderapprovalhistoryid()
    {
        return this.bidderapprovalhistoryid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bidderId ( INT ) 
    public void setBidderid( Integer bidderid )
    {
        this.bidderid = bidderid;
    }
    public Integer getBidderid()
    {
        return this.bidderid;
    }

    //--- DATABASE MAPPING : companyId ( INT ) 
    public void setCompanyid( Integer companyid )
    {
        this.companyid = companyid;
    }
    public Integer getCompanyid()
    {
        return this.companyid;
    }

    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : envelopeId ( INT ) 
    public void setEnvelopeid( Integer envelopeid )
    {
        this.envelopeid = envelopeid;
    }
    public Integer getEnvelopeid()
    {
        return this.envelopeid;
    }

    //--- DATABASE MAPPING : finalSubmissionId ( INT ) 
    public void setFinalsubmissionid( Integer finalsubmissionid )
    {
        this.finalsubmissionid = finalsubmissionid;
    }
    public Integer getFinalsubmissionid()
    {
        return this.finalsubmissionid;
    }

    //--- DATABASE MAPPING : isApproved ( INT ) 
    public void setIsapproved( Integer isapproved )
    {
        this.isapproved = isapproved;
    }
    public Integer getIsapproved()
    {
        return this.isapproved;
    }

    //--- DATABASE MAPPING : remarks ( LONGTEXT ) 
    public void setRemarks( String remarks )
    {
        this.remarks = remarks;
    }
    public String getRemarks()
    {
        return this.remarks;
    }

    //--- DATABASE MAPPING : tenderId ( INT ) 
    public void setTenderid( Integer tenderid )
    {
        this.tenderid = tenderid;
    }
    public Integer getTenderid()
    {
        return this.tenderid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(bidderapprovalhistoryid);
        sb.append("]:"); 
        sb.append(bidderid);
        sb.append("|");
        sb.append(companyid);
        sb.append("|");
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        sb.append("|");
        sb.append(envelopeid);
        sb.append("|");
        sb.append(finalsubmissionid);
        sb.append("|");
        sb.append(isapproved);
        // attribute 'remarks' not usable (type = String Long Text)
        sb.append("|");
        sb.append(tenderid);
        return sb.toString(); 
    } 

}