/*
 * Created on 24 Nov 2016 ( Time 10:54:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "tbl_company"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_company")
public class TblCompany implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="companyid", nullable=false)
    public Integer    companyid    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="companyName", nullable=false)
    private String     companyname  ;

    @Column(name="createdBy", nullable=false)
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn", nullable=false)
    private Date       createdon    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(fetch=FetchType.LAZY,mappedBy="tblCompany", targetEntity=TblFinalsubmission.class)
    private List<TblFinalsubmission> listOfTblFinalsubmission;

    @OneToMany(fetch=FetchType.LAZY,mappedBy="tblCompany", targetEntity=TblTenderbidconfirmation.class)
    private List<TblTenderbidconfirmation> listOfTblTenderbidconfirmation;

    @OneToMany(fetch=FetchType.LAZY,mappedBy="tblCompany", targetEntity=TblTenderopen.class)
    private List<TblTenderopen> listOfTblTenderopen;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblCompany()
    {
		super();
    }
    public TblCompany(int companyid){
        this.companyid = companyid;
    }
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCompanyid( Integer companyid )
    {
        this.companyid = companyid ;
    }
    public Integer getCompanyid()
    {
        return this.companyid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : companyName ( LONGTEXT ) 
    public void setCompanyname( String companyname )
    {
        this.companyname = companyname;
    }
    public String getCompanyname()
    {
        return this.companyname;
    }

    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTblFinalsubmission( List<TblFinalsubmission> listOfTblFinalsubmission )
    {
        this.listOfTblFinalsubmission = listOfTblFinalsubmission;
    }
    public List<TblFinalsubmission> getListOfTblFinalsubmission()
    {
        return this.listOfTblFinalsubmission;
    }

    public void setListOfTblTenderbidconfirmation( List<TblTenderbidconfirmation> listOfTblTenderbidconfirmation )
    {
        this.listOfTblTenderbidconfirmation = listOfTblTenderbidconfirmation;
    }
    public List<TblTenderbidconfirmation> getListOfTblTenderbidconfirmation()
    {
        return this.listOfTblTenderbidconfirmation;
    }

    public void setListOfTblTenderopen( List<TblTenderopen> listOfTblTenderopen )
    {
        this.listOfTblTenderopen = listOfTblTenderopen;
    }
    public List<TblTenderopen> getListOfTblTenderopen()
    {
        return this.listOfTblTenderopen;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(companyid);
        sb.append("]:"); 
        // attribute 'companyname' not usable (type = String Long Text)
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        return sb.toString(); 
    } 

}