/*
 * Created on 24 Nov 2016 ( Time 10:54:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

/**
 * Persistent class for entity stored in table "tbl_finalsubmission"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_finalsubmission")
public class TblFinalsubmission implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="finalSubmissionId",unique = true, nullable=false)
    private Integer    finalsubmissionid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="consortiumId", nullable=true)
    private Integer    consortiumid ;

    @Column(name="partnerType", nullable=true)
    private Integer    partnertype  ;

    @Column(name="isActive", nullable=false)
    private Integer    isactive     ;

    @Column(name="createdBy", nullable=false)
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn",nullable=false,updatable=false,insertable=false)
    private Date       createdon    ;

    @Column(name="ipAddress", nullable=false)
    private String     ipaddress    ;

    @Column(name="bidderid", nullable=false)
    private Integer    bidderid     ;

	// "companyid" (column "companyid") is not defined by itself because used as FK in a link 
	// "tenderid" (column "tenderid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tenderid", referencedColumnName="tenderId")
    private TblTender tblTender   ;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="companyid", referencedColumnName="companyid")
    private TblCompany tblCompany  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblFinalsubmission()
    {
		super();
    }
    
    public TblFinalsubmission(int finalsubmissionid){
        this.finalsubmissionid = finalsubmissionid;
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFinalsubmissionid( Integer finalsubmissionid )
    {
        this.finalsubmissionid = finalsubmissionid ;
    }
    public Integer getFinalsubmissionid()
    {
        return this.finalsubmissionid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : consortiumId ( INT ) 
    public void setConsortiumid( Integer consortiumid )
    {
        this.consortiumid = consortiumid;
    }
    public Integer getConsortiumid()
    {
        return this.consortiumid;
    }

    //--- DATABASE MAPPING : partnerType ( INT ) 
    public void setPartnertype( Integer partnertype )
    {
        this.partnertype = partnertype;
    }
    public Integer getPartnertype()
    {
        return this.partnertype;
    }

    //--- DATABASE MAPPING : isActive ( INT ) 
    public void setIsactive( Integer isactive )
    {
        this.isactive = isactive;
    }
    public Integer getIsactive()
    {
        return this.isactive;
    }

    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : ipAddress ( LONGTEXT ) 
    public void setIpaddress( String ipaddress )
    {
        this.ipaddress = ipaddress;
    }
    public String getIpaddress()
    {
        return this.ipaddress;
    }

    //--- DATABASE MAPPING : bidderid ( INT ) 
    public void setBidderid( Integer bidderid )
    {
        this.bidderid = bidderid;
    }
    public Integer getBidderid()
    {
        return this.bidderid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTblTender( TblTender tblTender )
    {
        this.tblTender = tblTender;
    }
    public TblTender getTblTender()
    {
        return this.tblTender;
    }

    public void setTblCompany( TblCompany tblCompany )
    {
        this.tblCompany = tblCompany;
    }
    public TblCompany getTblCompany()
    {
        return this.tblCompany;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(finalsubmissionid);
        sb.append("]:"); 
        sb.append(consortiumid);
        sb.append("|");
        sb.append(partnertype);
        sb.append("|");
        sb.append(isactive);
        sb.append("|");
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        // attribute 'ipaddress' not usable (type = String Long Text)
        sb.append("|");
        sb.append(bidderid);
        return sb.toString(); 
    } 

}