/*
 * Created on 22 Nov 2016 ( Time 07:58:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "tbl_link"
 *
 *
 */

@Entity
@Table(name="tbl_link")
public class TblLink implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer    linkId       ;
    private String     linkName     ;
    private String     module       ;
    private String     link         ;
    private String     description  ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblLink() {
		super();
    }
    
    public TblLink(int linkId) {
		this.linkId=linkId;
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setLinkId( Integer linkId ) {
        this.linkId = linkId ;
    }
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="linkId", nullable=false)
    public Integer getLinkId() {
        return this.linkId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : linkName ( VARCHAR ) 
    public void setLinkName( String linkName ) {
        this.linkName = linkName;
    }
    @Column(name="linkName", nullable=false, length=25)
    public String getLinkName() {
        return this.linkName;
    }

    //--- DATABASE MAPPING : module ( VARCHAR ) 
    public void setModule( String module ) {
        this.module = module;
    }
    @Column(name="module", length=25)
    public String getModule() {
        return this.module;
    }

    //--- DATABASE MAPPING : link ( VARCHAR ) 
    public void setLink( String link ) {
        this.link = link;
    }
    @Column(name="link", nullable=false, length=50)
    public String getLink() {
        return this.link;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    @Column(name="description", nullable=false, length=50)
    public String getDescription() {
        return this.description;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    
    
    private Set<TblRoleLinkMapping> listOfTblRolelinkmapping;
    public void setListOfTblRolelinkmapping( Set<TblRoleLinkMapping> listOfTblRolelinkmapping ) {
        this.listOfTblRolelinkmapping = listOfTblRolelinkmapping;
    }
    @OneToMany(mappedBy="tblLink",cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    public Set<TblRoleLinkMapping> getListOfTblRolelinkmapping() {
        return this.listOfTblRolelinkmapping;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(linkId);
        sb.append("]:"); 
        sb.append(linkName);
        sb.append("|");
        sb.append(module);
        sb.append("|");
        sb.append(link);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}
