/*
 * Created on 22 Jan 2017 ( Time 23:23:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "tbl_purchaseorder"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_purchaseorder")
public class TblPurchaseorder implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="poId", nullable=false)
    private Integer    poid         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="poNumber", nullable=false, length=25)
    private String     ponumber     ;

    
    
    
    @Column(name="deptId", nullable=false)
    private Integer    deptid       ;

    @Column(name="bidderId", nullable=false)
    private Integer    bidderid     ;

    @Column(name="bidderRef", length=100)
    private String     bidderref    ;

    @Column(name="brifDetail", nullable=false, length=500)
    private String     brifdetail   ;

    @Column(name="projectDetail", length=500)
    private String     projectdetail ;

    @Column(name="consigneeDetails", nullable=false, length=500)
    private String     consigneedetails ;

    @Column(name="deliverySchedule", nullable=false, length=500)
    private String     deliveryschedule ;

    @Column(name="modeOfTransport", length=500)
    private String     modeoftransport ;

    @Column(name="inspection", nullable=false, length=500)
    private String     inspection   ;

    @Column(name="contractValue", nullable=false)
    private Integer    contractvalue ;

    @Column(name="performanceBank", nullable=false, length=100)
    private String     performancebank ;

    @Column(name="paymentDetail", nullable=false, length=500)
    private String     paymentdetail ;

    @Column(name="payingAuthority", nullable=false, length=100)
    private String     payingauthority ;

    @Column(name="projectEstimation", length=500)
    private String     projectestimation ;

    @Column(name="technicalSpecification", length=500)
    private String     technicalspecification ;

    @Column(name="poTermsAndCond", length=500)
    private String     potermsandcond ;

    @Column(name="poAmount", nullable=false)
    private Integer    poamount     ;
    @Column(name="createdOn", nullable=false)
    private Date       createdOn    ;
    @Column(name="cstatus")
    private int       cstatus   ;
    
    @Column(name="tenderId",nullable=false)
    private int       tenderId   ;

    @Column(name="remarks", length=500)
    private String     remarks ;
    
    @Column(name="isAcknowledge")
    private int       isAcknowledge   ;
    
    @Column(name="rowId")
    private int       rowId   ;
    
    @Column(name="formId")
    private int       formId   ;
    
    @Column(name="tableId")
    private int       tableId   ;
    
    @Column(name="ItemDesc")
    private String     ItemDesc ;
    
    
    
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblPurchaseorder() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    
    
    
    
    public void setPoid( Integer poid ) {
        this.poid = poid ;
    }
    public String getItemDesc() {
		return ItemDesc;
	}

	public void setItemDesc(String itemDesc) {
		ItemDesc = itemDesc;
	}

	public int getFormId() {
		return formId;
	}

	public void setFormId(int formId) {
		this.formId = formId;
	}

	public int getTableId() {
		return tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	public int getRowId() {
		return rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public int getIsAcknowledge() {
		return isAcknowledge;
	}

	public void setIsAcknowledge(int isAcknowledge) {
		this.isAcknowledge = isAcknowledge;
	}

	public int getTenderId() {
		return tenderId;
	}

	public void setTenderId(int tenderId) {
		this.tenderId = tenderId;
	}

	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public int getCstatus() {
		return cstatus;
	}

	public void setCstatus(int cstatus) {
		this.cstatus = cstatus;
	}

	public Integer getPoid() {
        return this.poid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : poNumber ( VARCHAR ) 
    public void setPonumber( String ponumber ) {
        this.ponumber = ponumber;
    }
    public String getPonumber() {
        return this.ponumber;
    }

    //--- DATABASE MAPPING : deptId ( INT ) 
    public void setDeptid( Integer deptid ) {
        this.deptid = deptid;
    }
    public Integer getDeptid() {
        return this.deptid;
    }

    //--- DATABASE MAPPING : bidderId ( INT ) 
    public void setBidderid( Integer bidderid ) {
        this.bidderid = bidderid;
    }
    public Integer getBidderid() {
        return this.bidderid;
    }

    //--- DATABASE MAPPING : bidderRef ( VARCHAR ) 
    public void setBidderref( String bidderref ) {
        this.bidderref = bidderref;
    }
    public String getBidderref() {
        return this.bidderref;
    }

    //--- DATABASE MAPPING : brifDetail ( VARCHAR ) 
    public void setBrifdetail( String brifdetail ) {
        this.brifdetail = brifdetail;
    }
    public String getBrifdetail() {
        return this.brifdetail;
    }

    //--- DATABASE MAPPING : projectDetail ( VARCHAR ) 
    public void setProjectdetail( String projectdetail ) {
        this.projectdetail = projectdetail;
    }
    public String getProjectdetail() {
        return this.projectdetail;
    }

    //--- DATABASE MAPPING : consigneeDetails ( VARCHAR ) 
    public void setConsigneedetails( String consigneedetails ) {
        this.consigneedetails = consigneedetails;
    }
    public String getConsigneedetails() {
        return this.consigneedetails;
    }

    //--- DATABASE MAPPING : deliverySchedule ( VARCHAR ) 
    public void setDeliveryschedule( String deliveryschedule ) {
        this.deliveryschedule = deliveryschedule;
    }
    public String getDeliveryschedule() {
        return this.deliveryschedule;
    }

    //--- DATABASE MAPPING : modeOfTransport ( VARCHAR ) 
    public void setModeoftransport( String modeoftransport ) {
        this.modeoftransport = modeoftransport;
    }
    public String getModeoftransport() {
        return this.modeoftransport;
    }

    //--- DATABASE MAPPING : inspection ( VARCHAR ) 
    public void setInspection( String inspection ) {
        this.inspection = inspection;
    }
    public String getInspection() {
        return this.inspection;
    }

    //--- DATABASE MAPPING : contractValue ( INT ) 
    public void setContractvalue( Integer contractvalue ) {
        this.contractvalue = contractvalue;
    }
    public Integer getContractvalue() {
        return this.contractvalue;
    }

    //--- DATABASE MAPPING : performanceBank ( VARCHAR ) 
    public void setPerformancebank( String performancebank ) {
        this.performancebank = performancebank;
    }
    public String getPerformancebank() {
        return this.performancebank;
    }

    //--- DATABASE MAPPING : paymentDetail ( VARCHAR ) 
    public void setPaymentdetail( String paymentdetail ) {
        this.paymentdetail = paymentdetail;
    }
    public String getPaymentdetail() {
        return this.paymentdetail;
    }

    //--- DATABASE MAPPING : payingAuthority ( VARCHAR ) 
    public void setPayingauthority( String payingauthority ) {
        this.payingauthority = payingauthority;
    }
    public String getPayingauthority() {
        return this.payingauthority;
    }

    //--- DATABASE MAPPING : projectEstimation ( VARCHAR ) 
    public void setProjectestimation( String projectestimation ) {
        this.projectestimation = projectestimation;
    }
    public String getProjectestimation() {
        return this.projectestimation;
    }

    //--- DATABASE MAPPING : technicalSpecification ( VARCHAR ) 
    public void setTechnicalspecification( String technicalspecification ) {
        this.technicalspecification = technicalspecification;
    }
    public String getTechnicalspecification() {
        return this.technicalspecification;
    }

    //--- DATABASE MAPPING : poTermsAndCond ( VARCHAR ) 
    public void setPotermsandcond( String potermsandcond ) {
        this.potermsandcond = potermsandcond;
    }
    public String getPotermsandcond() {
        return this.potermsandcond;
    }

    //--- DATABASE MAPPING : poAmount ( INT ) 
    public void setPoamount( Integer poamount ) {
        this.poamount = poamount;
    }
    public Integer getPoamount() {
        return this.poamount;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(poid);
        sb.append("]:"); 
        sb.append(ponumber);
        sb.append("|");
        sb.append(deptid);
        sb.append("|");
        sb.append(bidderid);
        sb.append("|");
        sb.append(bidderref);
        sb.append("|");
        sb.append(brifdetail);
        sb.append("|");
        sb.append(projectdetail);
        sb.append("|");
        sb.append(consigneedetails);
        sb.append("|");
        sb.append(deliveryschedule);
        sb.append("|");
        sb.append(modeoftransport);
        sb.append("|");
        sb.append(inspection);
        sb.append("|");
        sb.append(contractvalue);
        sb.append("|");
        sb.append(performancebank);
        sb.append("|");
        sb.append(paymentdetail);
        sb.append("|");
        sb.append(payingauthority);
        sb.append("|");
        sb.append(projectestimation);
        sb.append("|");
        sb.append(technicalspecification);
        sb.append("|");
        sb.append(potermsandcond);
        sb.append("|");
        sb.append(poamount);
        return sb.toString(); 
    } 

}
