/*
 * Created on 30 Nov 2016 ( Time 11:16:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**not in used
 * Persistent class for entity stored in table "tbl_rebatedetail"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_rebatedetail")
public class TblRebateDetail implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="rebateDetailId",unique=true, nullable=false)
    private Integer    rebatedetailid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="cellValue", nullable=false)
    private String     cellvalue    ;

    @Column(name="createdBy", nullable=false)
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn", nullable=false)
    private Date       createdon    ;

	// "companyid" (column "companyid") is not defined by itself because used as FK in a link 
	// "tenderid" (column "tenderid") is not defined by itself because used as FK in a link 
	// "bidtableid" (column "bidtableid") is not defined by itself because used as FK in a link 
	// "cellid" (column "cellid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="columnId", referencedColumnName="columnId")
    private TblTenderColumn tblTendercolumn;

    @ManyToOne
    @JoinColumn(name="companyid", referencedColumnName="companyid")
    private TblCompany tblCompany  ;

    @ManyToOne
    @JoinColumn(name="bidtableid", referencedColumnName="bidTableId")
    private TblTenderBidMatrix tblTenderbidmatrix;

    @ManyToOne
    @JoinColumn(name="tenderid", referencedColumnName="tenderId")
    private TblTender tblTender   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblRebateDetail()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRebatedetailid( Integer rebatedetailid )
    {
        this.rebatedetailid = rebatedetailid ;
    }
    public Integer getRebatedetailid()
    {
        return this.rebatedetailid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : cellValue ( LONGTEXT ) 
    public void setCellvalue( String cellvalue )
    {
        this.cellvalue = cellvalue;
    }
    public String getCellvalue()
    {
        return this.cellvalue;
    }

    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTendercolumn( TblTenderColumn tblTendercolumn )
    {
        this.tblTendercolumn = tblTendercolumn;
    }
    public TblTenderColumn getTblTendercolumn()
    {
        return this.tblTendercolumn;
    }

    public void setTblCompany( TblCompany tblCompany )
    {
        this.tblCompany = tblCompany;
    }
    public TblCompany getTblCompany()
    {
        return this.tblCompany;
    }

    public void setTblTenderbidmatrix( TblTenderBidMatrix tblTenderbidmatrix )
    {
        this.tblTenderbidmatrix = tblTenderbidmatrix;
    }
    public TblTenderBidMatrix getTblTenderbidmatrix()
    {
        return this.tblTenderbidmatrix;
    }

    public void setTblTender( TblTender tblTender )
    {
        this.tblTender = tblTender;
    }
    public TblTender getTblTender()
    {
        return this.tblTender;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(rebatedetailid);
        sb.append("]:"); 
        // attribute 'cellvalue' not usable (type = String Long Text)
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        return sb.toString(); 
    } 

}