/*
 * Created on 30 Nov 2016 ( Time 11:16:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "tbl_tenderbidmatrix"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_tenderbidmatrix")
public class TblTenderBidMatrix implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="bidTableId",unique=true, nullable=false)
    private Integer    bidtableid   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bidJson", nullable=false)
    private String     bidjson      ;

    @Column(name="encryptedBid")
    private String     encryptedbid ;

	// "bidid" (column "bidid") is not defined by itself because used as FK in a link 
	// "tableid" (column "tableid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="bidid", referencedColumnName="bidId")
    private TblTenderBid tblTenderbid;

    @OneToMany(mappedBy="tblTenderbidmatrix", targetEntity=TblTenderBidOpenSign.class)
    private List<TblTenderBidOpenSign> listOfTblTenderbidopensign;

    @OneToMany(mappedBy="tblTenderbidmatrix", targetEntity=TblRebateDetail.class)
    private List<TblRebateDetail> tblRebateDetail;

    @ManyToOne
    @JoinColumn(name="tableid", referencedColumnName="tableId")
    private TblTenderTable tblTendertable;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblTenderBidMatrix()
    {
		super();
    }
    public TblTenderBidMatrix(Integer bidtableid)
    {
		this.bidtableid= bidtableid;
    }
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBidtableid( Integer bidtableid )
    {
        this.bidtableid = bidtableid ;
    }
    public Integer getBidtableid()
    {
        return this.bidtableid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bidJson ( LONGTEXT ) 
    public void setBidjson( String bidjson )
    {
        this.bidjson = bidjson;
    }
    public String getBidjson()
    {
        return this.bidjson;
    }

    //--- DATABASE MAPPING : encryptedBid ( LONGTEXT ) 
    public void setEncryptedbid( String encryptedbid )
    {
        this.encryptedbid = encryptedbid;
    }
    public String getEncryptedbid()
    {
        return this.encryptedbid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTblTenderbid( TblTenderBid tblTenderbid )
    {
        this.tblTenderbid = tblTenderbid;
    }
    public TblTenderBid getTblTenderbid()
    {
        return this.tblTenderbid;
    }

    public void setListOfTblTenderbidopensign( List<TblTenderBidOpenSign> listOfTblTenderbidopensign )
    {
        this.listOfTblTenderbidopensign = listOfTblTenderbidopensign;
    }
    public List<TblTenderBidOpenSign> getListOfTblTenderbidopensign()
    {
        return this.listOfTblTenderbidopensign;
    }

    public void setListOfTblRebatedetail( List<TblRebateDetail> listOfTblRebatedetail )
    {
        this.tblRebateDetail = listOfTblRebatedetail;
    }
    public List<TblRebateDetail> getListOfTblRebatedetail()
    {
        return this.tblRebateDetail;
    }

    public void setTblTendertable( TblTenderTable tblTendertable )
    {
        this.tblTendertable = tblTendertable;
    }
    public TblTenderTable getTblTendertable()
    {
        return this.tblTendertable;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(bidtableid);
        sb.append("]:"); 
        // attribute 'bidjson' not usable (type = String Long Text)
        // attribute 'encryptedbid' not usable (type = String Long Text)
        return sb.toString(); 
    } 

}