/*
 * Created on 24 Nov 2016 ( Time 10:54:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "tbl_tenderopen"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_tenderopen")
public class TblTenderopen implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="tenderOpenId", nullable=false)
    private Integer    tenderopenid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bidSignData")
    private String     bidsigndata  ;

    @Column(name="createdBy", nullable=false)
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn", nullable=false,updatable=false,insertable=false)
    private Date       createdon    ;
    
    @Column(name="bidderid", nullable=false)
    private Integer    bidderid     ;

    
    @Column(name="decryptionLevel", nullable=false)
    private Integer    decryptionlevel ;

    @Column(name="ipAddress", nullable=false)
    private String     ipaddress    ;
    
    //--- DATABASE MAPPING : bidderid ( INT ) 
    public void setBidderid( Integer bidderid )
    {
        this.bidderid = bidderid;
    }
    public Integer getBidderid()
    {
        return this.bidderid;
    }


	// "companyid" (column "companyid") is not defined by itself because used as FK in a link 
	// "tenderid" (column "tenderid") is not defined by itself because used as FK in a link 
	// "envelopeid" (column "envelopeid") is not defined by itself because used as FK in a link 
	// "formid" (column "formid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="companyid", referencedColumnName="companyid")
    private TblCompany tblCompany  ;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="formid", referencedColumnName="formId")
    private TblTenderForm tblTenderform;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="envelopeid", referencedColumnName="envelopeId")
    private TblTenderEnvelope tblTenderenvelope;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tenderid", referencedColumnName="tenderId")
    private TblTender tblTender   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblTenderopen()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTenderopenid( Integer tenderopenid )
    {
        this.tenderopenid = tenderopenid ;
    }
    public Integer getTenderopenid()
    {
        return this.tenderopenid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bidSignData ( LONGTEXT ) 
    public void setBidsigndata( String bidsigndata )
    {
        this.bidsigndata = bidsigndata;
    }
    public String getBidsigndata()
    {
        return this.bidsigndata;
    }

    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : decryptionLevel ( INT ) 
    public void setDecryptionlevel( Integer decryptionlevel )
    {
        this.decryptionlevel = decryptionlevel;
    }
    public Integer getDecryptionlevel()
    {
        return this.decryptionlevel;
    }

    //--- DATABASE MAPPING : ipAddress ( LONGTEXT ) 
    public void setIpaddress( String ipaddress )
    {
        this.ipaddress = ipaddress;
    }
    public String getIpaddress()
    {
        return this.ipaddress;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTblCompany( TblCompany tblCompany )
    {
        this.tblCompany = tblCompany;
    }
    public TblCompany getTblCompany()
    {
        return this.tblCompany;
    }

    public void setTblTenderForm( TblTenderForm tblTenderform )
    {
        this.tblTenderform = tblTenderform;
    }
    public TblTenderForm getTblTenderform()
    {
        return this.tblTenderform;
    }

    public void setTblTenderenvelope( TblTenderEnvelope tblTenderenvelope )
    {
        this.tblTenderenvelope = tblTenderenvelope;
    }
    public TblTenderEnvelope getTblTenderenvelope()
    {
        return this.tblTenderenvelope;
    }

    public void setTblTender( TblTender tblTender )
    {
        this.tblTender = tblTender;
    }
    public TblTender getTblTender()
    {
        return this.tblTender;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(tenderopenid);
        sb.append("]:"); 
        // attribute 'bidsigndata' not usable (type = String Long Text)
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        sb.append("|");
        sb.append(decryptionlevel);
        sb.append("|");
        sb.append(bidderid);
        // attribute 'ipaddress' not usable (type = String Long Text)
        return sb.toString(); 
    } 

}