/*
 * Created on 29 Nov 2016 ( Time 11:52:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.math.BigDecimal;
import java.util.Date;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.OneToMany;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "tbl_tenderbid"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_tenderbid")
public class TblTenderBid implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="bidId",unique=true, nullable=false)
    private Integer    bidid        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bidPrice")
    private BigDecimal bidprice     ;

    @Column(name="createdBy", nullable=false)
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn",nullable=false,updatable=false,insertable=false)
    private Date       createdon    ;

    @Column(name="cstatus", nullable=false)
    private Integer    cstatus      ;

    @Column(name="ipAddress", nullable=false)
    private String     ipaddress    ;

    @Column(name="bidderid", nullable=false)
    private Integer    bidderid     ;
    @Column(name="formBidWeight")
    private Double formBidWeight = 0.0 ;
    
    

	// "companyid" (column "companyid") is not defined by itself because used as FK in a link 
	// "tenderid" (column "tenderid") is not defined by itself because used as FK in a link 
	// "envelopeid" (column "envelopeid") is not defined by itself because used as FK in a link 
	// "formid" (column "formid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="formid", referencedColumnName="formId")
    private TblTenderForm tblTenderform;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tenderid", referencedColumnName="tenderId")
    private TblTender tblTender   ;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="envelopeid", referencedColumnName="envelopeId")
    private TblTenderEnvelope tblTenderenvelope;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="companyid", referencedColumnName="companyid")
    private TblCompany tblCompany  ;

    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblTenderBid()
    {
		super();
    }
    public TblTenderBid(int bidid){
        this.bidid = bidid;
    }
    public TblTenderBid(int bidid,int cstatus,String ipaddress){
        this.bidid = bidid;
        this.cstatus =cstatus;
        this.ipaddress = ipaddress;
    }
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBidid( Integer bidid )
    {
        this.bidid = bidid ;
    }
    public Integer getBidid()
    {
        return this.bidid;
    }

   
    public Double getFormBidWeight() {
		return formBidWeight;
	}
	public void setFormBidWeight(Double formBidWeight) {
		this.formBidWeight = formBidWeight;
	}
	//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bidPrice ( DECIMAL ) 
    public void setBidprice( BigDecimal bidprice )
    {
        this.bidprice = bidprice;
    }
    public BigDecimal getBidprice()
    {
        return this.bidprice;
    }

    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : cstatus ( INT ) 
    public void setCstatus( Integer cstatus )
    {
        this.cstatus = cstatus;
    }
    public Integer getCstatus()
    {
        return this.cstatus;
    }

    //--- DATABASE MAPPING : ipAddress ( LONGTEXT ) 
    public void setIpaddress( String ipaddress )
    {
        this.ipaddress = ipaddress;
    }
    public String getIpaddress()
    {
        return this.ipaddress;
    }

    //--- DATABASE MAPPING : bidderid ( INT ) 
    public void setBidderid( Integer bidderid )
    {
        this.bidderid = bidderid;
    }
    public Integer getBidderid()
    {
        return this.bidderid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTblTenderform( TblTenderForm tblTenderform )
    {
        this.tblTenderform = tblTenderform;
    }
    public TblTenderForm getTblTenderform()
    {
        return this.tblTenderform;
    }

    public void setTblTender( TblTender tblTender )
    {
        this.tblTender = tblTender;
    }
    public TblTender getTblTender()
    {
        return this.tblTender;
    }

    public void setTblTenderenvelope( TblTenderEnvelope tblTenderenvelope )
    {
        this.tblTenderenvelope = tblTenderenvelope;
    }
    public TblTenderEnvelope getTblTenderenvelope()
    {
        return this.tblTenderenvelope;
    }

    public void setTblCompany( TblCompany tblCompany )
    {
        this.tblCompany = tblCompany;
    }
    public TblCompany getTblCompany()
    {
        return this.tblCompany;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(bidid);
        sb.append("]:"); 
        sb.append(bidprice);
        sb.append("|");
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        sb.append("|");
        sb.append(cstatus);
        // attribute 'ipaddress' not usable (type = String Long Text)
        sb.append("|");
        sb.append(bidderid);
        return sb.toString(); 
    } 

}