/*
 * Created on 30 Nov 2016 ( Time 11:16:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

/**
 * Persistent class for entity stored in table "tbl_tenderbidopensign"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_tenderbidopensign")
public class TblTenderBidOpenSign implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="bidOpenSignId",unique = true, nullable=false)
    private Integer    bidopensignid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bidSignText")
    private String     bidsigntext  ;

    @Column(name="createdBy")
    private Integer    createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn")
    private Date       createdon    ;

    @Column(name="decryptedBid")
    private String     decryptedbid ;

	// "bidtableid" (column "bidtableid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="bidtableid", referencedColumnName="bidTableId")
    private TblTenderBidMatrix tblTenderbidmatrix;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblTenderBidOpenSign()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBidopensignid( Integer bidopensignid )
    {
        this.bidopensignid = bidopensignid ;
    }
    public Integer getBidopensignid()
    {
        return this.bidopensignid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bidSignText ( LONGTEXT ) 
    public void setBidsigntext( String bidsigntext )
    {
        this.bidsigntext = bidsigntext;
    }
    public String getBidsigntext()
    {
        return this.bidsigntext;
    }

    //--- DATABASE MAPPING : createdBy ( INT ) 
    public void setCreatedby( Integer createdby )
    {
        this.createdby = createdby;
    }
    public Integer getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : createdOn ( DATETIME ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : decryptedBid ( LONGTEXT ) 
    public void setDecryptedbid( String decryptedbid )
    {
        this.decryptedbid = decryptedbid;
    }
    public String getDecryptedbid()
    {
        return this.decryptedbid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTblTenderbidmatrix( TblTenderBidMatrix tblTenderbidmatrix )
    {
        this.tblTenderbidmatrix = tblTenderbidmatrix;
    }
    public TblTenderBidMatrix getTblTenderbidmatrix()
    {
        return this.tblTenderbidmatrix;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(bidopensignid);
        sb.append("]:"); 
        // attribute 'bidsigntext' not usable (type = String Long Text)
        sb.append(createdby);
        sb.append("|");
        sb.append(createdon);
        // attribute 'decryptedbid' not usable (type = String Long Text)
        return sb.toString(); 
    } 

}