/*
 * Created on 30 Nov 2016 ( Time 12:58:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eprocurement.etender.model;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "tbl_tenderbiddetail"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tbl_tenderbiddetail")
public class TblTenderBidDetail implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="bidDetailId",unique=true, nullable=false)
    private Integer    biddetailid  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="cellNo", nullable=false)
    private Integer    cellno       ;

    @Column(name="cellValue", nullable=false)
    private String     cellvalue    ;

	// "bidtableid" (column "bidtableid") is not defined by itself because used as FK in a link 
	// "cellid" (column "cellid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="cellid", referencedColumnName="cellId")
    private TblTenderCell tblTendercell;

    @ManyToOne
    @JoinColumn(name="bidtableid", referencedColumnName="bidTableId")
    private TblTenderBidMatrix tblTenderbidmatrix;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TblTenderBidDetail()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBiddetailid( Integer biddetailid )
    {
        this.biddetailid = biddetailid ;
    }
    public Integer getBiddetailid()
    {
        return this.biddetailid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : cellNo ( INT ) 
    public void setCellno( Integer cellno )
    {
        this.cellno = cellno;
    }
    public Integer getCellno()
    {
        return this.cellno;
    }

    //--- DATABASE MAPPING : cellValue ( LONGTEXT ) 
    public void setCellvalue( String cellvalue )
    {
        this.cellvalue = cellvalue;
    }
    public String getCellvalue()
    {
        return this.cellvalue;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTblTendercell( TblTenderCell tblTendercell )
    {
        this.tblTendercell = tblTendercell;
    }
    public TblTenderCell getTblTendercell()
    {
        return this.tblTendercell;
    }

    public void setTblTenderbidmatrix( TblTenderBidMatrix tblTenderbidmatrix )
    {
        this.tblTenderbidmatrix = tblTenderbidmatrix;
    }
    public TblTenderBidMatrix getTblTenderbidmatrix()
    {
        return this.tblTenderbidmatrix;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(biddetailid);
        sb.append("]:"); 
        sb.append(cellno);
        // attribute 'cellvalue' not usable (type = String Long Text)
        return sb.toString(); 
    } 

}